### ISSUE TITLE
Update documentation for creating source-git repositories

### ISSUE THREAD

**Issue by csomh** [packit/packit.dev#281]
The documentation [to create source-git repositories](https://packit.dev/docs/source-git/how-to-source-git/) is outdated. Update it, to match the latest format of the source-git repos.

Changes to include:
- The directory to hold packaging files is called `.distro`, not `fedora`.
- Instead of creating `packit.yaml` in the repo root, create `./distro/source-git.yaml`.
- The content of `.distro/source-git.yaml` is:
    ```yaml
    ---
    downstream_package_name: <package_name>
    upstream_ref: <ref where the downstream branch starts>
    patch_generation_ignore_paths:
      - .distro/
    sync_changelog: true
    synced_files:
      - src: .distro/
        dest: .
        delete: true
        filters:
          - "protect .git*"
          - "protect sources"
          - "exclude source-git.yaml"
          - "exclude .gitignore"
     ```
- Also create `.distro/.gitignore` with the content bellow in order to reset possible top-level ignore-rules (downstream packaging files might need different ones):
    ```
    # Reset ignore rules for .distro
    !
    ```
- One could use the following `rsync` command to get content from the dist-git repository into the `.distro` sub-directory (this is the reverse of what `packit` does, when updating the dist-git repo). Note, that the trailing slash at the end of `rpms/<package>/` is relevant:
    
      $ rsync --archive --delete --filter 'protect source-git.yaml' --filter 'protect .gitignore' --filter 'exclude sources' --filter 'exclude .git*' rpms/<package>/ .distro/
