### ISSUE TITLE
Cannot print nor evaluate envars in `fix-spec-file`

### ISSUE THREAD

**Issue by pirat89** [packit/packit.dev#334]
```yaml
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: packaging/leapp-repository.spec

actions:
  create-archive:
  - ....whatever you need...
  fix-spec-file:
  - bash -c echo AAAAAAAAA $PACKIT_PROJECT_VERSION
```

output for `packit --debug srpm`:
```
[snip]
2021-09-14 16:52:45.086 commands.py       DEBUG  Command: bash -c echo AAAAAAAAA $PACKIT_PROJECT_VERSION
2021-09-14 16:52:45.091 logging.py        INFO   
2021-09-14 14:52:45.214 lookaside_cache_helper.py WARNING "sources" is not a file, skipping parsing it
[snip]
```
As a consequence, I am not even able to update the spec by any command.

Other info:
- packit-0.35.0-1.fc33.noarch
- Fedora 33

-----
PEBKAC *palmface* - this works:
```yaml
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: packaging/leapp-repository.spec

actions:
  create-archive:
  - ....whatever you need...
  fix-spec-file:
  - bash -c "echo AAAAAAAAA $PACKIT_PROJECT_VERSION"
```
