### ISSUE TITLE
GitLab pipelines support

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit.dev#470]
@mfocko has tried to run packit in GitLab.ci and it looks really nice and easy to set up.

The definition is really easy ([example](https://gitlab.com/mfocko/karel-the-robot/-/merge_requests/1/diffs)):

```yaml
image: quay.io/packit/packit

srpm_build:
  stage: build
  script:
  - packit srpm
  artifacts:
    paths:
      - "*.src.rpm"
    expire_in: 1 week
```

As you can see, the definition is explicit, uses directly our image and does not have any unnecessary information. And also, we don't need to maintain that anyhow..;) 

And it looks like this:
* pipeline: https://gitlab.com/mfocko/karel-the-robot/-/pipelines/549111019
* logs: https://gitlab.com/mfocko/karel-the-robot/-/jobs/2511715361
* artifacts: https://gitlab.com/mfocko/karel-the-robot/-/jobs/2511715361/artifacts/browse (not the file itself, no `zip` as with GitHub..;) 

So, what we can do?

* [ ] Document this use case on our documentation page.
* [ ] Setup a repository with the config examples.

That's easy to do and can be a nice benefit to GitLab users without much work from our side.
