### ISSUE TITLE
Running packit as a service for forks

### ISSUE THREAD

**Issue by LecrisUT** [packit/packit.dev#631]
It would be nice to have some configurable options that can override the `.packit.yaml` through the service so that packit can run on github forks and copr forks. E.g. the upstream might define:
```yaml
jobs:
  - job: copr_build
    trigger: commit
    owner: "@upstream_group"
    project: CI
    branch: main
```
But on your fork you want to edit it to something like:
```yaml
jobs:
  - job: copr_build
    trigger: commit
    owner: forking_user
    project: CI
    branch: develop_branch
```
Ideally you don't want to rebase back-and-forth so much just to enable this testing. It would be nice to have it editable in either the github app interface or via the `packit` cli such that you can add/replace `jobs` per repository.

Benefit:
- Allows to run CI jobs on individual users before submitting PRs
- Allows to create packit setup on forks that do not want to include this dependency upstream
