### ISSUE TITLE
Document the ‹propose-downstream› workflow for CentOS Stream

### ISSUE THREAD

**Issue by mfocko** [packit/packit.dev#796]
Document the way to enable `propose-downstream` workflow for the CentOS Stream. This must be done using 2 different packages (since they don't share packaging tool, and it's also beneficial to have them separate because of potentially different specfiles being used).

Example of such config:
```yaml
---
downstream_package_name: nispor
upstream_project_url: https://github.com/nispor/nispor
issue_repository: https://github.com/nispor/nispor
update_release: false
upstream_package_name: nispor
upstream_tag_template: v{version}
copy_upstream_release_description: false

packages:
  nispor-fedora:
    actions:
      post-upstream-clone:
        - wget https://src.fedoraproject.org/rpms/nispor/raw/rawhide/f/nispor.spec
  nispor-centos:
    pkg_tool: centpkg
    actions:
      post-upstream-clone:
        - wget https://gitlab.com/redhat/centos-stream/rpms/nispor/-/raw/c9s/nispor.spec

jobs:
  - job: propose_downstream
    trigger: release
    packages: [nispor-fedora]
    dist_git_branches:
      - fedora

  - job: propose_downstream
    trigger: release
    packages: [nispor-centos]
    dist_git_branches:
      - c9s
```
